from os import system
from colorama import Fore
from time import sleep
system("clear")
print()
print()
print()
print(Fore.GREEN+"["+Fore.RED+"~"+Fore.GREEN+"]"+Fore.WHITE+"Hello my friend, welcome to the tool")
print()
ip = input(Fore.GREEN+"""
  [1] ip Target
  [2] number Target
  [3] Exit
  Please select a number"""+Fore.RED+" > ")

if ip == "1":
  print()
  print(Fore.GREEN+"please wite.....")
  sleep(1)
  system("clear")
  print()
  print(Fore.RED+"  ("+Fore.WHITE+"   IP Attacker Target  "+Fore.RED+"  )")
  print()
  print(Fore.GREEN+"My ID Telegram > "+Fore.WHITE+"https://t.me/Number_1235")
  print(Fore.GREEN+"Chanel Telgram > "+Fore.WHITE+"https://t.me/Cyber_Seven")
  print(Fore.GREEN+"Chanel Telegram 2 > "+Fore.WHITE+"https://t.me/DARK_MICE")
  print()
  ip = input(Fore.YELLOW+"please IP Target "+Fore.RED+"> "+Fore.BLUE)
  print()
  sleep(2)
  print()
  print(Fore.GREEN+"=========== "+Fore.WHITE+"MR.DARK"+Fore.GREEN+" ===========")
  print()
  print(Fore.YELLOW+"IP Address "+Fore.BLUE+": "+Fore.GREEN+ip)
  print(Fore.YELLOW+"City "+Fore.BLUE+": "+Fore.GREEN+"America")
  print(Fore.YELLOW+"Region "+Fore.BLUE+": "+Fore.GREEN+"Brelin")
  print(Fore.YELLOW+"Country "+Fore.BLUE+": "+Fore.GREEN+"America")
  print(Fore.YELLOW+"Latitude "+Fore.BLUE+": "+Fore.GREEN+"30.1754")
  print(Fore.YELLOW+"Time Zone "+Fore.BLUE+": "+Fore.GREEN+"America/English")
  print(Fore.YELLOW+"Postal Code "+Fore.BLUE+": "+Fore.GREEN+"6544")
  print(Fore.YELLOW+"ASN "+Fore.BLUE+": "+Fore.GREEN+"A123564")
  print(Fore.YELLOW+"Country Code "+Fore.BLUE+": "+Fore.GREEN+"EN")
  print(Fore.YELLOW+"Currency "+Fore.BLUE+": "+Fore.GREEN+"Dollar")
  print(Fore.YELLOW+"Calling Code "+Fore.BLUE+": "+Fore.GREEN+"+1")
  print()
  exit()

if ip == "2":
  print()
  print(Fore.GREEN+"please wite.....")
  sleep(1)
  system("clear")
  print()
  print(Fore.RED+"  ("+Fore.WHITE+"   number Attacker  "+Fore.RED+"  )")
  print()
  print(Fore.GREEN+"My ID Telegram > "+Fore.WHITE+"https://t.me/Number_1235")
  print(Fore.GREEN+"Chanel Telgram > "+Fore.WHITE+"https://t.me/Cyber_Seven")
  print(Fore.GREEN+"Chanel Telegram 2 > "+Fore.WHITE+"https://t.me/DARK_MICE")
  print()
  number = input(Fore.YELLOW+"please number Target (+98XXXXXXX) "+Fore.RED+"> "+Fore.BLUE)
  print()
  sleep(2)
  print()
  print(Fore.GREEN+"=========== "+Fore.WHITE+"MR.DARK"+Fore.GREEN+" ===========")
  print()
  print(Fore.YELLOW+"location "+Fore.BLUE+": "+Fore.GREEN+"Iran")
  print(Fore.YELLOW+"number Target "+Fore.BLUE+": "+Fore.GREEN+number)
  print(Fore.YELLOW+"Type number "+Fore.BLUE+": "+Fore.GREEN+"True")
  print(Fore.YELLOW+"number "+Fore.BLUE+": "+Fore.GREEN+"True")
  print(Fore.YELLOW+"mobile network "+Fore.BLUE+": "+Fore.GREEN+"Irancell")
  print(Fore.YELLOW+"Type "+Fore.BLUE+": "+Fore.GREEN+"The mobile number")
  print(Fore.YELLOW+"Country code "+Fore.BLUE+": "+Fore.GREEN+"+98")
  print(Fore.YELLOW+"E.164 format "+Fore.BLUE+": "+Fore.GREEN+ip)
  exit()
else:
  exit()
if name == "3":
  exit()
